pipeline {
        agent any
        tools {
            jdk 'jdk8'
            maven 'Mvn1'   
        } 
        stages {       
            stage('install') {  
                steps {               
                    sh 'mvn clean install'                      
                }  
                post {
                    always {
                        junit '**/target/*-reports/TEST-*.xml' 
                    }
                }     
            } 
            
        }
    }